language: python

python:
  - "3.6"

branches:
  only:
    - master

install:
  - pip install pip==18.0
  - pip install pipenv==2018.11.26
  - npm install -g now serverless

script:
  - cd api
  - npm install
  - pipenv update
  - bin/deploy stable
  - pipenv install git+https://github.com/ambv/black.git#egg=black
  - bin/deploy master
  - cd ../web
  # - npm install
  # - now --token=$NOW_TOKEN --public
  # - now --token=$NOW_TOKEN alias
  # - now --token=$NOW_TOKEN remove --safe --yes black || true
